#!/bin/bash

. ~/.shell-colors

if [ -z "$1" ]; then 
	echo -e "\n $red   OOPS...\n    Usage: dubb-short movie_name\n $reset"
	exit
fi
# printf " \t  $yell  Add time for conversion (in secs): \n \t [ or hit enter to convert the whole file ] \n \t :-  "
# read input
if [  "$input" = "" ]; then
	convtime=""
else
	convtime="-t $input"
fi
if [ -f "$1" ]; then
	echo -e "\n $cyan  *** Converting the movie - one pass ***\n"
	name=$(echo  $1 | cut -d "." -f1 | tr - _)
	name=./$name.1.avi
	echo -e "\n   ***Saving to $name***\n $green"
	starting_time=`date +%s`

	nice -n 8 ffmpeg $convtime -i $1 -y -threads 5 -s 720x400 -aspect 16:9 -f avi -vcodec mpeg4 -b 1100000 -qmax 8 -async 25 -acodec libmp3lame -ab 96k -ac 2 -vol 512 $name
	
	end_time=`date +%s`
	answer=$(($end_time-$starting_time))
	[ "$answer" -ge "60" ] && \
		minutes=$(($answer/60)) && seconds=$(($answer-($minutes*60))) && \
		printf "\n $cyan   $minutes mins $seconds secs overall... \n \n" || \
		printf "\n $cyan $answer seconds overall... \n\n"
		
	echo -e "\n $yell   ALL DONE NOW   !!!\n $reset"
else
	echo -e "\n $red  Wrong name for movie... \n   Try Again $reset \n"
fi
exit 0
