#!/bin/bash

## Quickly checks if I have new gmail

outtox=0
[[ "$1" != "" ]] && outtox=1
tmp=/tmp/gmail_check.atomfeed
[[ -f $tmp ]] || touch $tmp
mssg=""

wget -T 3 -t 1 -q --secure-protocol=TLSv1 \
 --no-check-certificate \
 --user=moetunes111 --password="f0*fO?W3(((" \
 https://mail.google.com/mail/feed/atom -O $tmp

if [ "$(wc -l $tmp | awk '{print $1}')" -lt "2" ]; then
    if [ "$outtox" -lt "1" ]; then
        echo -e "   GMAIL CHECK FAILED   \n       CHECK NEEDED     \n" |\
            xmessage -center -file -
     else
        echo -e "   GMAIL CHECK FAILED   \n       CHECK NEEDED     \n"
     fi
    exit 1
fi 

have_mail=`sed -n 's|<fullcount>\(.*\)</fullcount>|\1|p' $tmp`
how_many=`grep -c "<contributor>" $tmp`
let have_mail=(${have_mail}+$how_many)
what_mail=`sed -n 's|<title>\(.*\)</title>|\1|p' $tmp`
#echo "$what_mail"
i=0

if [ $have_mail -gt "0" ]; then
    mssg="   You have new gmail.  \n"
    mssg="$mssg   There are:\n      $have_mail new messages\n\n"
    while read -r line; do
        if [ "$i" -lt "1" ]; then
            mssg="$mssg   $line\n"
        else
            mssg="$mssg      $line\n"
        fi
        ((++i))
    done < <(echo "$what_mail")
    if [ "$outtox" -lt "1" ]; then
        echo -e "$mssg" | xmessage -center -file -
     else
         echo -e "$mssg"
     fi
else
    mssg="   No new gmail.  "
    [[ "$outtox" -lt "1" ]] && echo -e "$mssg" | xmessage -center -timeout 4 -file - ||\
     echo -e "$mssg"
fi

exit 0
